config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => "admin#index"

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    
    resources :products do
      get :who_bought, :on => :member
    end

    root :to => 'store#index', :as => 'store' # :as creates a path variable, in this case store_path
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <%= stylesheet_link_tag "scaffolds", "application" %>
    <%= stylesheet_link_tag "depot" , :media => "all" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "prototype", "scriptaculous"%>
    <%= csrf_meta_tag %>
  </head>
  <body id="store">
    <div id="banner">
      <%= image_tag("logo.png" ) %>
      <%= @page_title || t('.title') %>
    </div>
    <div id="columns">
      <div id="side">
	<% if @cart %>
	  <%= hidden_div_if(@cart.line_items.empty?, :id => "cart" ) do %>
	    <%= render @cart  %>
	  <% end %>
	<% end %>
	<a href="http://www...."><%= t('.home') %></a><br />
	<a href="http://www..../faq"><%= t('.questions') %></a><br />
	<a href="http://www..../news"><%= t('.news') %></a><br />
	<a href="http://www..../contact"><%= t('.contact') %></a><br />
	<a href="#"> <%= Time.now %></a>
	
	<% if session[:user_id] %>
	  <br />
	  <%= link_to 'Orders', orders_path %>
	  <%= link_to 'Products', products_path %>
	  <%= link_to 'Users', users_path %>
	  <br />
	  
	  <%= button_to 'Logout', logout_path, :method => :delete, :confirmation => 'Do you want to logging out?'%>
	<% end %>
	
      </div>
      <div id="main">
	<%= yield %>
      </div>
    </div>
  </body>
</html>